### ISSUE TITLE
Complete language implementation

### ISSUE THREAD

**Issue by pradal** [AgriculturalModelExchangeInitiative/SQ_Wheat_Phenology#1]
Add implementation for:
- [x] C++
- [x] Fortran
- [x] Java

**Comment by cyrillemidingoyi** [comment]
C++ and Java already done. But some mistake wth the compilation of fortran code. Please check the example I push

**Comment by cyrillemidingoyi** [comment]
@pradal 
Fortran done
I created a module named Crop2mlModules to implement fibonacci function, indice function ( retrieve an index of element in a vector) and some subroutines used to add an element in a dynamic array
